#include "main.h"

/**
 * sigint_handler - handles the SIGINT signal
 * @signal: the signal number
 
 * Description: This function is called when the SIGINT signal is received,
 * typically generated by pressing Ctrl+C. It writes a newline character to
 * the standard output, prompts for a new command, and flushes the output buffer.
 *
 * Return: void
 */
void sigint_handler(int signal)
{
	if (signal == SIGINT)
	{
		write(STDOUT_FILENO, "\n", 1);
		prompt();
		fflush(stdout);
	}
}
